### ISSUE TITLE
Python 3.12: `imp` has been removed, please use importlib instead

### ISSUE THREAD

**Issue by sanjayankur31** [return42/fspath#3]
Fedora is rebuilding all its Python packages with Python 3.12  at the moment in our development release. fspath fails to currently build because it uses the `imp` module, which was removed in Python 3.12. The suggested replacement is to use importlib.

https://docs.python.org/3.12/whatsnew/3.12.html#removed

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/ZTID6MR7TU2X6ZKDGGH7RR426ODUEENX/

**Comment by return42** [comment]
https://github.com/return42/fspath/blob/3085b785eee3a5b0f921d7e0d39b304c9b56a623/setup.py#L23

@sanjayankur31 @musicinmybrain thanks for pointing out / FYI linuxdoc is also affected:

- https://github.com/return42/linuxdoc/issues/33

**Comment by return42** [comment]
FYI new release v20230629 is available at pypi

- https://pypi.org/project/fspath/20230629/

**Comment by musicinmybrain** [comment]
Awesome! Thanks!
